version: "2.2"
services:
  tidlc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    image: dhsshine/tidlc:latest
    command: ['/bin/bash']
    tty: true
    stdin_open: true
    init: true
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
